name: Trivy Security Scan for NGINX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Scan nginx:latest with Trivy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Date
        id: set-date
        run: echo "DATE=$(date +%m.%d.%Y)" >> $GITHUB_ENV

      - name: Create output directory
        run: mkdir -p "GitHub Actions/Trivy Automation"

      - name: Install Trivy and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.57.0

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Download Trivy vulnerability database
        run: trivy image --download-db-only

      - name: Run Trivy vulnerability scanner
        run: |
          OUTPUT_FILE="GitHub Actions/Trivy Automation/scan-results-${DATE}.json"
          mkdir -p "GitHub Actions/Trivy Automation"
          # Removemos a opção --ignore-unfixed para exibir todas as vulnerabilidades
          trivy image --format json --vuln-type os,library --severity CRITICAL,HIGH,MEDIUM,LOW -o "$OUTPUT_FILE" nginx:latest
          echo "Trivy scan complete. Results saved to $OUTPUT_FILE."
          echo "Full scan results:"
          cat "$OUTPUT_FILE"
          if grep -q '"Severity": "HIGH"' "$OUTPUT_FILE"; then
            echo "High severity vulnerabilities found."
          else
            echo "No high severity vulnerabilities found."
          fi

      - name: Commit scan results if high vulnerabilities exist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if grep -q '"Severity": "HIGH"' "GitHub Actions/Trivy Automation/scan-results-${DATE}.json"; then
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add "GitHub Actions/Trivy Automation/scan-results-${DATE}.json"
            git commit -m "Add Trivy scan results (${DATE}) - High severity vulnerabilities found"
            git push origin HEAD:main
          else
            echo "No high severity vulnerabilities found. Not committing scan results."
          fi
